[package]
name = "levinstien-rs"
version = "0.1.0"
authors = ["Unnikrishnan Nair, Rahul <rahulunair@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.57.0"
cc = "1.0.67"
